# Fluid theme overrides.
fun_features:
  typing:
    startDelay: 500
    typeSpeed: 85
    backDelay: 3000
    backSpeed: 50
    cursorChar: "_"
    loop: true
    scope:
      - home

post:
  mermaid:
    enable: true
    specific: false
    options:
      theme: default
